### PR TITLE
Adding confirmation popup when user tries to go back.

### PR DESCRIPTION
**Pull request by mukulsinghal407**

### CODE REVIEW

**Comment by mukulsinghal407** [comment]
This pull request has an alert message for the user in case s/he presses the back to the home button by chance.

**Review by yashchaudhari008 — CHANGES_REQUESTED** [review]
Sorry, but Responsive UI is in progress (other contributors are already working on it).
Though I like the backtohome function.
move that somewhere in to index.js.

I suggest you to use `git revert ebf3bc653c8de4a665ae7d01c8b5cd05fb6d7a5f` and revert current changes and add backtohome function only.
Thanks!

**Comment by mukulsinghal407** [comment]
Ok, no problem !!
I would revert all the changes and just add the back-to-home function in the index.js.

**Comment by mukulsinghal407** [comment]
Hey, there using git revert bf1e819af280fe8b23c1e8ff2295255122c5eda3 said bad object so I deleted my fork and forked the project all over again. Should I close this pull request and add make a new one for you to merge?
@yashchaudhari008

**Comment by yashchaudhari008** [comment]
Use GitHub Desktop and revert commit. Do not delete fork and resubmit same PR.

**Comment by mukulsinghal407** [comment]
Well, I have deleted my fork already stupid me, how should I proceed now?
I am so sorry I am not that proficient with GitHub and git bash

**Comment by yashchaudhari008** [comment]
> Well, I have deleted my fork already stupid me, how should I proceed now? I am so sorry I am not that proficient with GitHub and git bash

😅I will close this PR then, hoping you learned not to delete forks, branch as you can revert them.
For now submit a new PR. I will mark this one duplicate and accept new one.

**Pull request closed without merging**
