### PR TITLE
#48 Changing background colour clears the canvas

### LINKED ISSUE #48: Changing background colour clears the canvas
As captioned, the fix should keep the current drawing while only changing the background colour.

Please assign this issue to me @yashchaudhari008.

### PR DESCRIPTION
**Pull request by brunojuliao**
I hope it works this time.

### CODE REVIEW

**Comment by yashchaudhari008** [comment]
image
Not resolved!

**Comment by yashchaudhari008** [comment]
I think the bug is fixed. I will check further and will let you know soon✌️

**Review by yashchaudhari008 — CHANGES_REQUESTED** [review]
Can you add some comments stating what actually functions do.
Namely mergeBgAndDrawing and seperateBgAndDrawings

**Comment by yashchaudhari008** [comment]
I updated few lines for finalizing, just add comments now for the function you create (also for statements if necessary)

**Comment by brunojuliao** [comment]
Please, confirm if the comments are good 😇

**Pull request merged**
